matrix:
  include:
    - os: osx
      osx_image: xcode9.3
script:
  - cd URITemplate && echo "IPHONEOS_DEPLOYMENT_TARGET = 8.0" > ios.xcconfig && swift package generate-xcodeproj --xcconfig-overrides ios.xcconfig && cd ..
  - xcodebuild -project Mockingjay.xcodeproj -scheme URITemplate-Package build -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild -project Mockingjay.xcodeproj -scheme Mockingjay -destination "platform=iOS Simulator,name=iPhone X" test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - pod lib lint --quick
